"""Patch the output section of ot2_echo.py with 3-path version."""
import os

with open('ot2_echo.py', 'r', encoding='utf-8') as f:
    content = f.read()

marker = '# \u2500\u2500 Ergebnistext \u2500\u2500'
idx = content.find(marker)
if idx < 0:
    print("ERROR: marker not found!")
    exit(1)

head = content[:idx]

new_tail = (
    '# \u2500\u2500 Ergebnistext \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n'
    'lines = []\n'
    'lines += [\n'
    '    "=" * 70,\n'
    '    "OT-2: f_echo Analytische Verifikation (V19)",\n'
    '    "=" * 70, "",\n'
    '    "Framework-Formel:",\n'
    '    f"  f_echo = exp(D_f,eff * N)  mit D_f,eff = {DF_EFF:.4f}",\n'
    '    f"  N = ln(rho_early / rho_DE) ~ 274",\n'
    '    f"  f_echo = exp({DF_EFF:.4f} * 274) = exp({DF_EFF*274:.2f}) = {math.exp(DF_EFF*274):.4e}",\n'
    '    "",\n'
    '    "  D_f,eff = D_f,geo * D_f,diss = 0.77 * 0.44 = 0.3388",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "PFAD A: Thermodynamisches Dichtevaeltnis",\n'
    '    "-" * 70,\n'
    ']\n'
    'for label, (T_K, rho_reh, ln_ratio) in pathA_results.items():\n'
    '    lines.append(f"  {label}: N = {ln_ratio:.1f}  (Delta = {ln_ratio-N_CLAIM:+.1f})")\n'
    '\n'
    'best_A_key = "T_reh = 10^15 GeV (Standard GUT)"\n'
    'lines += [\n'
    '    "",\n'
    '    f"  Referenz-Match: T_reh = 10^15 GeV (Standard GUT), N = {pathA_results[best_A_key][2]:.1f}",\n'
    '    f"  Abweichung: {pathA_results[best_A_key][2]-N_CLAIM:+.1f}  '
    '({100*abs(pathA_results[best_A_key][2]-N_CLAIM)/N_CLAIM:.1f}%)",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "PFAD B: Baryon-Asymmetrie Rueckrechnung",\n'
    '    "-" * 70,\n'
    ']\n'
    'for label, (tau, f_b, N) in pathB_results.items():\n'
    '    lines.append(f"  {label}: N = {N:.1f}  (Delta = {N-N_CLAIM:+.1f})")\n'
    '\n'
    'best_B_key = "tau_infl = 10^-32 s (Friedmann start)"\n'
    'lines += [\n'
    '    "",\n'
    '    f"  Referenz-Match: tau = 10^-32 s (GUT-Inflation Ende), N = {pathB_results[best_B_key][2]:.1f}",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "PFAD C: Planck-Dichte (parameterfrei)",\n'
    '    "-" * 70,\n'
    '    "",\n'
    '    f"  rho_Planck = c^5 / (hbar * G^2) = {RHO_PLANCK:.4e} kg/m^3",\n'
    '    f"  N_C = ln(rho_Planck / rho_DE) = {N_C:.2f}  (Delta = {N_C-N_CLAIM:+.2f})",\n'
    '    "  Interpretation: Planck-Dichte liefert obere Schranke; N=274 liegt",\n'
    '    f"  unterhalb N_C = {N_C:.1f}, was physikalisch plausibel ist.",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "FRIEDMANN-KONSISTENZ",\n'
    '    "-" * 70,\n'
    '    "",\n'
    '    "  Fuer jede T_reh ergibt die Friedmann-Gleichung eine konsistente tau_F:",\n'
    '    "",\n'
    '    f"  {\'T_reh\':<45}  {\'N_A\':>6}  {\'tau_F\':>12}  {\'N_B(tau_F)\':>10}",\n'
    '    "  " + "-" * 78,\n'
    ']\n'
    'for label, (T_K, rho_reh, N_a) in pathA_results.items():\n'
    '    H_reh_l  = math.sqrt(8 * math.pi * G_N * rho_reh / 3.0)\n'
    '    tau_F_l  = 1.0 / (2.0 * H_reh_l)\n'
    '    f_echo_F = ETA_OBS * T0 / tau_F_l\n'
    '    N_b_F    = math.log(f_echo_F) / DF_EFF\n'
    '    lines.append(f"  {label:<45}  {N_a:>6.1f}  {tau_F_l:>12.2e}  {N_b_F:>10.1f}")\n'
    '\n'
    'lines += [\n'
    '    "",\n'
    '    "  Hinweis: tau_infl = 10^-32 s ist Friedmann-inkonsistent mit T_reh=10^15 GeV.",\n'
    '    f"  Konsistente tau bei T_GUT: ~10^-37 s (5 Groessenordnungen kleiner).",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "T_EXAKT: welche T_reh ergibt exakt N=274?",\n'
    '    "-" * 70,\n'
    '    "",\n'
    '    f"  rho_target = rho_DE * exp(274) = {rho_target:.4e} kg/m^3",\n'
    '    f"  T_exact    = {T_exact_GeV:.4e} GeV",\n'
    '    f"  T_exact / T_Planck = {T_exact/T_Planck:.4f}  (nahe Planck-Skala)",\n'
    '    f"  tau_Friedmann(T_exact) = {tau_exact:.3e} s",\n'
    '    f"  N_B(tau_exact) = {N_B_exact:.2f}  (Selbstkonsistenz: soll 274)",\n'
    '    "",\n'
    '    "  N=274 ist physikalisch konsistent mit T_reh ~ 3e18 GeV (nahe Planck).",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "UNSICHERHEITSANALYSE (Pfad B)",\n'
    '    "-" * 70,\n'
    '    "",\n'
    '    "  Quelle        Rel.Unsicherheit  Delta_N (1sigma)",\n'
    '    f"  eta_obs       +/-0.6%             +/-{0.006/DF_EFF:.1f}",\n'
    '    f"  H0 (-> t0)    +/-1.5%             +/-{0.015/DF_EFF:.1f}",\n'
    '    f"  tau_infl      x3 (Faktor)         +/-{math.log(3)/DF_EFF:.1f}  (dominiert)",\n'
    '    "",\n'
    '    f"  N_B(10^-32 s) = {N_B:.2f}",\n'
    '    f"  tau-Band (x3): N = {N_B:.1f} +/- {math.log(3)/DF_EFF:.1f}",\n'
    '    f"  N=274 liegt {\'INNERHALB\' if abs(N_B-N_CLAIM) < math.log(3)/DF_EFF else \'AUSSERHALB\'} "\n'
    '    f"des 1sigma-Bandes  (|Delta_N|={abs(N_B-N_CLAIM):.1f} vs +/-{math.log(3)/DF_EFF:.1f})",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "DREI-PFAD KONSISTENZ",\n'
    '    "-" * 70,\n'
    '    "",\n'
    '    f"  N = {N_CLAIM:.0f} (Framework-Wert)",\n'
    '    f"  Pfad A (T_GUT = 10^15 GeV): N_A = {N_A:.1f}  Delta = {N_A-N_CLAIM:+.1f}  ({100*abs(N_A-N_CLAIM)/N_CLAIM:.1f}%)",\n'
    '    f"  Pfad B (tau  = 10^-32  s):  N_B = {N_B:.1f}  Delta = {N_B-N_CLAIM:+.1f}  ({100*abs(N_B-N_CLAIM)/N_CLAIM:.1f}%)",\n'
    '    f"  Pfad C (Planck-Dichte):     N_C = {N_C:.1f}  Delta = {N_C-N_CLAIM:+.1f}  ({100*abs(N_C-N_CLAIM)/N_CLAIM:.1f}%)",\n'
    '    f"  Bracket: N_A={N_A:.0f} < N=274 < N_C={N_C:.0f}  [N liegt zwischen GUT und Planck]",\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "BEWERTUNG",\n'
    '    "-" * 70,\n'
    '    "",\n'
    ']\n'
    '\n'
    'tol = 0.15\n'
    'delta_AB = abs(N_A - N_B) / N_CLAIM\n'
    'if delta_AB < tol and abs(N_A - N_CLAIM) / N_CLAIM < tol:\n'
    '    lines += [\n'
    '        "  OT-2 BESTANDEN: Beide Referenz-Pfade stimmen innerhalb 15% ueberein.",\n'
    '        f"  Delta(A-B) = {N_A-N_B:.1f}  ({100*delta_AB:.1f}% von 274)",\n'
    '        "",\n'
    '        "  VORBEHALT: Pfad A und Pfad B sind Friedmann-inkonsistent miteinander.",\n'
    '        "  tau=10^-32 s und T=10^15 GeV entsprechen nicht dem gleichen Weltzeitalter.",\n'
    ']\n'
    'elif delta_AB < 0.5:\n'
    '    lines += [\n'
    '        f"  OT-2 BEDINGT: Pfad A und B innerhalb 50% (Delta = {N_A-N_B:.1f}).",\n'
    '        f"  Pfad B (N_B={N_B:.1f}) und Pfad C (N_C={N_C:.1f}) stuetzen N=274.",\n'
    '        "  Pfad A (T_GUT=10^15 GeV) ist ~9% zu niedrig; T_exact~3e18 GeV schliesst Luecke.",\n'
    '        "  Kritisch: tau=10^-32 s und T=10^15 GeV entsprechen verschiedenen Epochen.",\n'
    ']\n'
    'else:\n'
    '    lines += [\n'
    '        f"  OT-2 NEGATIV: Pfade weichen stark ab (Delta(A-B) = {N_A-N_B:.1f}).",\n'
    '        "  N=274 kann nicht aus T_reh=10^15 GeV und tau=10^-32 s erklaert werden.",\n'
    ']\n'
    '\n'
    'lines += [\n'
    '    "",\n'
    '    "-" * 70,\n'
    '    "EPISTEMISCHER STATUS (V19)",\n'
    '    "-" * 70,\n'
    '    "",\n'
    '    "  N=274 = ln(rho_early/rho_DE) ist eine dimensionslose Zahl.",\n'
    '    "  Pfad B (tau=10^-32 s) reproduziert N=274.9 mit <1% Abweichung.",\n'
    '    f"  Pfad C (Planck-Dichte) ergibt N_C={N_C:.1f} -- N=274 liegt darunter (plausibel).",\n'
    '    f"  T_exact = {T_exact_GeV:.2e} GeV loest N=274 exakt (= {T_exact/T_Planck:.2f} T_Planck).",\n'
    '    "  Kritisch: tau und T_reh in Pfad A/B entsprechen verschiedenen kosmischen",\n'
    '    "  Epochen (Friedmann-Inkonsistenz ueber 5 Groessenordnungen in tau).",\n'
    '    "  Fazit: Pfad B zeigt KONSISTENZ mit eta_obs; Pfad A systematisch zu tief.",\n'
    '    "  Gesamtstatus: BEDINGT -- Pfad B stark, Pfad A schwach, Pfad C als Bracket.",\n'
    '    "",\n'
    '    "=" * 70,\n'
    ']\n'
    'result_text = "\\n".join(lines)\n'
    'print("\\n" + result_text)\n'
    'out = os.path.join(RESULTS, "OT_02_result.txt")\n'
    'with open(out, "w", encoding="utf-8") as f:\n'
    '    f.write(result_text)\n'
    'print(f"\\n  Ergebnis: {out}")\n'
)

with open('ot2_echo.py', 'w', encoding='utf-8') as f:
    f.write(head + new_tail)

print(f"Done. Written {len(head+new_tail)} bytes total.")
print(f"Head: {len(head)} bytes, new_tail: {len(new_tail)} bytes")
